### ISSUE TITLE
Front-End Feedback

### ISSUE THREAD

**Issue by steven-juice** [oliskertch/landing-page#3]
Hi @oliskertch ,

Overall, it looks really good. Just a few pointers below with some links to some useful articles.

### HTML

* Header navigation items have an invalid href value
    * Can’t have spaces, if just using placeholders, can use “#”
* For text elements, can use header or paragraph tags instead of `<div>`
    * e.g. `<h1>, <p>`
* Examples of HTML element tags and their uses:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element
* Can use the blockquote element for the quote text:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote

### Styling

* When applying the same styling properties and values, you can group them together
    * style.css (line 32) cold become:
    * `a:link, a:visited, a:hover, a:active { text-decoration: none; }`
* **BEM** is good methodology for writing and using css classes:
    * https://css-tricks.com/bem-101/
    * Allows you add modifier classes, improves readability and re-usability
* **px** values are used a lot for spacing and font sizes
    * consider **rem** or **em** units, especially for fonts:
    * https://j.eremy.net/confused-about-rem-and-em/
    * If you set the base font size for the document to 62.5%, it allows you to correlate rem values to px easily
        * e.g. 1rem = 10px
        * `html { font-size: 62.5%;` }
        * `h1 { font-size: 1rem // same as 10px }`
        * Some browsers do not resize **px** values if a user zooms in, so using **rem** values makes the site more accessible.
* There is no maximum width of the container
    * On my larger screen, it fills the whole page:
    * ![Screenshot 2022-08-10 at 11 26 59](https://user-images.githubusercontent.com/87305014/183879521-9667c34d-86fc-4396-978d-f40d6053aa6c.png)
    * You can create a containing div either inside of each main element (header, footer etc.), or around all of them, and style as below to centre them:
    * `.container { max-width: 1280px *or* 128rem; margin: auto; }`
    * `margin: auto` centralises elements if their width is smaller than its container

**Comment by oliskertch** [comment]
Really useful feedback. Thank you!
